#This file stores configuration options for AngelicaShaders, such as the currently active shaderpack
#Thu Jul 23 18:18:29 CDT 2026
enableDebugOptions=false
disableUpdateMessage=true
enableShaders=false
maxShadowRenderDistance=12
allowUnknownShaders=false
shaderPack=BountifulStarsALPHA0.0.3.zip
