#This file stores configuration options for AngelicaShaders, such as the currently active shaderpack
#Thu Jul 30 11:48:09 MDT 2026
enableDebugOptions=false
disableUpdateMessage=true
enableShaders=false
maxShadowRenderDistance=12
allowUnknownShaders=false
shaderPack=BountifulStarsALPHA0.0.3.zip
