#This file stores configuration options for AngelicaShaders, such as the currently active shaderpack
#Sat Sep 05 12:13:21 MDT 2026
enableDebugOptions=false
disableUpdateMessage=true
enableShaders=true
maxShadowRenderDistance=12
allowUnknownShaders=false
shaderPack=BountifulStarsALPHA0.0.3.zip
