var pickaxes = <ore:allPickaxes>;

pickaxes.add(<minecraft:iron_pickaxe>);
pickaxes.add(<minecraft:stone_pickaxe>);
pickaxes.add(<minecraft:diamond_pickaxe>);
pickaxes.add(<minecraft:golden_pickaxe>);
pickaxes.add(<minecraft:wooden_pickaxe>);
pickaxes.add(<HardcoreEnderExpansion:schorching_pickaxe>);
pickaxes.add(<etfuturum:netherite_pickaxe>);
pickaxes.add(<hbm:item.dwarven_pickaxe>);
pickaxes.add(<hbm:item.schrabidium_pickaxe>);
pickaxes.add(<hbm:item.steel_pickaxe>);
pickaxes.add(<netherlicious:EfrinePickaxe>);
pickaxes.add(<imc:item_flint_pick>);
pickaxes.add(<imc:item_nether_brick_pickaxe>);
pickaxes.add(<hbm:item.mese_pickaxe>);
pickaxes.add(<hbm:item.chlorophyte_pickaxe>);
pickaxes.add(<hbm:item.volcanic_pickaxe>);
pickaxes.add(<hbm:item.bismuth_pickaxe>);
pickaxes.add(<hbm:item.desh_pickaxe>);
pickaxes.add(<hbm:item.cmb_pickaxe>);
pickaxes.add(<hbm:item.alloy_pickaxe>);
pickaxes.add(<hbm:item.starmetal_pickaxe>);
pickaxes.add(<hbm:item.cobalt_decorated_pickaxe>);
pickaxes.add(<hbm:item.cobalt_pickaxe>);
pickaxes.add(<hbm:item.titanium_pickaxe>);
