// File generated by MineTweakerRecipeMaker
//                     READ THIS HEADER BEFORE EDITING ANYTHING
// ================================================================================
//     This file is read and changed by the mod.
//     If you remove/edit any of the markers, IT WILL STOP WORKING!
//     If you want to make manual edits, make a backup of this file!
//     Markers look like this: "//#MARKER something"
//     They indicate where calls should be placed, so that MineTweaker does them in the correct order.
//     Removes come first, then stuff is added.
// ================================================================================
//

// ================================================================================
//#MARKER REMOVE
recipes.remove(<curvy_pipes:pipe:11>);
recipes.remove(<curvy_pipes:pipe:6>);
recipes.remove(<curvy_pipes:pipe:1>);
recipes.remove(<minecraft:iron_door>);

// ================================================================================
//#MARKER REMOVE SHAPELESS

// ================================================================================
//#MARKER REMOVE SHAPED

// ================================================================================
//#MARKER ADD

// ================================================================================
//#MARKER ADD SHAPELESS

// ================================================================================
//#MARKER ADD SHAPED
recipes.addShaped(<curvy_pipes:pipe:1>, [[<ore:ntmpipeCopper>, <ore:ntmpipeDuraSteel>, <ore:ntmpipeCopper>], [<ore:ntmpipeCopper>, <hbm:item.plate_desh>, <ore:ntmpipeCopper>], [<ore:ntmpipeCopper>, <ore:ntmpipeDuraSteel>, <ore:ntmpipeCopper>]]);
recipes.addShaped(<curvy_pipes:pipe:6>, [[null, <hbm:item.pipe:33>, null], [<hbm:item.pipe:20003>, <hbm:item.pipe:33>, <hbm:item.pipe:20003>], [null, <hbm:item.pipe:33>, null]]);
recipes.addShaped(<curvy_pipes:pipe:11>, [[<ore:ntmpipeRubber>, <hbm:tile.red_cable>, <ore:ntmpipeRubber>], [<ore:ntmpipeRubber>, <hbm:tile.red_cable>, <ore:ntmpipeRubber>], [<ore:ntmpipeRubber>, <hbm:tile.red_cable>, <ore:ntmpipeRubber>]]);
recipes.addShaped(<minecraft:iron_door>, [[<ore:ingotIron>, <ore:ingotIron>], [<ore:ingotIron>, <ore:ingotIron>], [<ore:ingotIron>, <ore:ingotIron>]]);

