name: Notify Leads and Admins

on:
  issues:
    types: [opened]

jobs:
  notify:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: "cc: @NTNewHorizons/leads @NTNewHorizons/admins"
            });
